'use client';

import { useCallback, useEffect, useState } from 'react';
import { Layers3, Loader2, Plus, RefreshCw } from 'lucide-react';
import { csrfFetch } from '@/shared/security/csrf-client';

type Collection = { id: string; name: string; slug: string; collectionType: 'CURATED' | 'RULE_BASED'; status: string; version: number; productIds?: string[]; visibleProducts?: { id: string }[] };

export default function CollectionsAdminPage() {
  const [collections, setCollections] = useState<Collection[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setLoading(true); const response = await fetch('/api/v1/admin/collections'); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Unable to load collections.'); setCollections(json.data || []); setError(null); } catch (err: any) { setError(err.message || 'Unable to load collections.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { const name = window.prompt('Collection name'); if (!name) return; const slug = name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); try { const response = await csrfFetch('/api/v1/admin/collections', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, slug, collectionType: 'CURATED' }) }); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Unable to create collection.'); await load(); } catch (err: any) { setError(err.message || 'Unable to create collection.'); } };
  const changeStatus = async (collection: Collection, action: 'publish' | 'archive') => { try { const response = await csrfFetch(`/api/v1/admin/collections/${collection.id}?action=${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version: collection.version }) }); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Unable to update collection.'); await load(); } catch (err: any) { setError(err.message || 'Unable to update collection.'); } };
  return <main className="space-y-6 p-4 sm:p-6"><header className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-2xl bg-indigo-50 p-3 text-indigo-600"><Layers3 className="h-6 w-6" /></div><div><h1 className="text-2xl font-black text-slate-900">Collections</h1><p className="text-sm text-slate-600">Curated and rule-based storefront groupings.</p></div></div><div className="flex gap-2"><button type="button" onClick={() => void create()} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-3 py-2 text-sm font-bold text-white"><Plus className="h-4 w-4" />New</button><button type="button" onClick={() => void load()} className="rounded-xl border border-slate-300 p-2"><RefreshCw className={loading ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} /></button></div></header>{error && <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{loading ? <div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" />Loading collections…</div> : collections.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No collections yet.</div> : <div className="grid gap-4">{collections.map((collection) => <article key={collection.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-black text-slate-900">{collection.name}</h2><p className="text-xs text-slate-500">/{collection.slug} · {collection.collectionType} · {collection.status}</p><p className="mt-2 text-xs text-slate-600">{collection.productIds?.length || 0} curated memberships</p></div><div className="flex gap-2">{collection.status === 'DRAFT' && <button type="button" onClick={() => void changeStatus(collection, 'publish')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Publish</button>}{collection.status === 'PUBLISHED' && <button type="button" onClick={() => void changeStatus(collection, 'archive')} className="rounded-lg bg-slate-700 px-3 py-2 text-xs font-bold text-white">Archive</button>}</div></div></article>)}</div>}</main>;
}
