/**
 * AlifWorld Immutable Audit Trail Interface & Action Constants
 * 
 * Captures actor, action, resource, before/after redaction-safe diffs,
 * request IDs, IP, user-agent, and timestamps for compliance and security forensics.
 * 
 * Invariants: ADR-0022, ADR-0031, NIST SP 800-63B, Milestone 040
 */

export const AUDIT_ACTIONS = {
  // Authentication & Session Lifecycle
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_TOKEN_ROTATED: 'AUTH_TOKEN_ROTATED',
  AUTH_BREACH_DETECTED: 'AUTH_BREACH_DETECTED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_SESSION_REVOKE_OTHERS: 'AUTH_SESSION_REVOKE_OTHERS',
  AUTH_SESSION_REVOKE_ALL: 'AUTH_SESSION_REVOKE_ALL',
  AUTH_RATE_LIMIT_EXCEEDED: 'AUTH_RATE_LIMIT_EXCEEDED',

  // Registration & Onboarding
  CUSTOMER_REGISTERED: 'CUSTOMER_REGISTERED',
  OAUTH_USER_REGISTERED: 'OAUTH_USER_REGISTERED',
  OAUTH_ACCOUNT_LINKED: 'OAUTH_ACCOUNT_LINKED',

  // Phone & SMS OTP Verification
  OTP_DISPATCHED: 'OTP_DISPATCHED',
  OTP_VERIFIED: 'OTP_VERIFIED',
  OTP_FAILED: 'OTP_FAILED',

  // Email Verification
  EMAIL_VERIFICATION_SENT: 'EMAIL_VERIFICATION_SENT',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',

  // Credential Security
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_CHANGE_FAILED: 'PASSWORD_CHANGE_FAILED',

  // Authorization & Tenancy
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REVOKED: 'ROLE_REVOKED',
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  AUTHZ_GRANTED: 'AUTHZ_GRANTED',
  AUTHZ_DENIED: 'AUTHZ_DENIED',
  AUTHZ_TENANT_VIOLATION: 'AUTHZ_TENANT_VIOLATION',
  AUTHZ_OWNERSHIP_VIOLATION: 'AUTHZ_OWNERSHIP_VIOLATION',
  AUTHZ_MAKER_CHECKER_REQUIRED: 'AUTHZ_MAKER_CHECKER_REQUIRED',

  // Order & Fulfillment Lifecycle
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  FULFILLMENT_GROUP_STATUS_CHANGED: 'FULFILLMENT_GROUP_STATUS_CHANGED',
  SHIPMENT_DISPATCHED: 'SHIPMENT_DISPATCHED',
  SHIPMENT_STATUS_UPDATED: 'SHIPMENT_STATUS_UPDATED',

  // Product Catalog & Merchant Inventory
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_PUBLISHED: 'PRODUCT_PUBLISHED',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  STOCK_RESERVED: 'STOCK_RESERVED',
  STOCK_COMMITTED: 'STOCK_COMMITTED',
  STOCK_RELEASED: 'STOCK_RELEASED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',

  // Merchant Store & KYC Compliance
  SELLER_REGISTERED: 'SELLER_REGISTERED',
  SELLER_KYC_SUBMITTED: 'SELLER_KYC_SUBMITTED',
  SELLER_KYC_VERIFIED: 'SELLER_KYC_VERIFIED',
  SELLER_KYC_REJECTED: 'SELLER_KYC_REJECTED',
  SELLER_SUSPENDED: 'SELLER_SUSPENDED',
  SELLER_REACTIVATED: 'SELLER_REACTIVATED',
  SELLER_SETTINGS_UPDATED: 'SELLER_SETTINGS_UPDATED',
  SELLER_STAFF_INVITED: 'SELLER_STAFF_INVITED',
  SELLER_STAFF_REMOVED: 'SELLER_STAFF_REMOVED',

  // Financial, Wallet & Double-Entry Ledger Operations
  WALLET_LEDGER_POSTED: 'WALLET_LEDGER_POSTED',
  PAYOUT_INITIATED: 'PAYOUT_INITIATED',
  PAYOUT_APPROVED: 'PAYOUT_APPROVED',
  PAYOUT_REJECTED: 'PAYOUT_REJECTED',
  PAYOUT_DISBURSED: 'PAYOUT_DISBURSED',
  MANUAL_BALANCE_ADJUSTED: 'MANUAL_BALANCE_ADJUSTED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  SETTLEMENT_BATCH_GENERATED: 'SETTLEMENT_BATCH_GENERATED',

  // Customer Support & Incident Resolution
  SUPPORT_TICKET_CREATED: 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_REPLIED: 'SUPPORT_TICKET_REPLIED',
  SUPPORT_TICKET_RESOLVED: 'SUPPORT_TICKET_RESOLVED',
  SUPPORT_TICKET_CLOSED: 'SUPPORT_TICKET_CLOSED',

  // Logistics & Delivery Operations
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  DELIVERY_ACCEPTED: 'DELIVERY_ACCEPTED',
  DELIVERY_PICKED_UP: 'DELIVERY_PICKED_UP',
  DELIVERY_COMPLETED: 'DELIVERY_COMPLETED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',

  // Security & Invariant Defenses
  SECURITY_ALERT_REFRESH_TOKEN_REUSE_DETECTED: 'SECURITY_ALERT_REFRESH_TOKEN_REUSE_DETECTED',
  CSRF_VIOLATION_DETECTED: 'CSRF_VIOLATION_DETECTED',
  CORS_VIOLATION_DETECTED: 'CORS_VIOLATION_DETECTED',
  PRIVILEGE_ESCALATION_PREVENTED: 'PRIVILEGE_ESCALATION_PREVENTED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  UNAUTHORIZED_RESOURCE_ACCESS: 'UNAUTHORIZED_RESOURCE_ACCESS',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS] | string;

export interface AuditStateDiff {
  [field: string]: {
    from: any;
    to: any;
  };
}

export interface AuditLogEntry {
  actorId?: string | null;
  actorRole?: string | null;
  action: AuditAction;
  resource: string;
  resourceId?: string | null;
  requestId?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  before?: Record<string, any> | null;
  after?: Record<string, any> | null;
  metadata?: Record<string, any> | null;
  createdAt?: Date;
}

export interface SanitizedAuditMetadata {
  requestId?: string | null;
  diff?: AuditStateDiff | null;
  [key: string]: any;
}

export interface AuditLogQueryParams {
  actorId?: string;
  actorRole?: string;
  action?: string;
  resource?: string;
  resourceId?: string;
  requestId?: string;
  startDate?: Date | string;
  endDate?: Date | string;
  page?: number;
  limit?: number;
}
