'use client';

import { useEffect, useState } from 'react';
import { csrfFetch } from '@/shared/security/csrf-client';

type Variant = { id: string; version: number; sku: string; title: string; pricePoisha: number; productPoint: number; isActive: boolean; displayOrder: number };

export default function ProductVariantManager({ productId }: { productId: string }) {
  const [variants, setVariants] = useState<Variant[]>([]);
  const [form, setForm] = useState({ sku: '', title: '', pricePoisha: '', productPoint: '0' });
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const load = async () => { const response = await fetch(`/api/v1/seller/catalog/products/${productId}/variants`); const body = await response.json().catch(() => null); if (!response.ok || !body?.success) throw new Error(body?.error?.message || 'Unable to load variants.'); setVariants(body.data || []); };
  useEffect(() => { void load().catch((err) => setError(err.message)); }, [productId]);
  const create = async () => { try { setSaving(true); setError(null); const response = await csrfFetch(`/api/v1/seller/catalog/products/${productId}/variants`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sku: form.sku, title: form.title, pricePoisha: Number(form.pricePoisha), productPoint: Number(form.productPoint), isActive: true, displayOrder: variants.length }) }); const body = await response.json().catch(() => null); if (!response.ok || !body?.success) throw new Error(body?.error?.message || 'Unable to create variant.'); setForm({ sku: '', title: '', pricePoisha: '', productPoint: '0' }); await load(); } catch (err: any) { setError(err.message || 'Unable to create variant.'); } finally { setSaving(false); } };
  const remove = async (variant: Variant) => { if (!window.confirm(`Delete ${variant.title}?`)) return; try { const response = await csrfFetch(`/api/v1/seller/catalog/products/${productId}/variants/${variant.id}?version=${variant.version}`, { method: 'DELETE' }); const body = await response.json().catch(() => null); if (!response.ok || !body?.success) throw new Error(body?.error?.message || 'Unable to delete variant.'); await load(); } catch (err: any) { setError(err.message || 'Unable to delete variant.'); } };
  return <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-lg font-black">Variants</h2><p className="mt-1 text-xs text-slate-400">Variant prices and Product Points are independent BDT/poisha values.</p>{error && <div role="alert" className="mt-3 rounded-lg bg-rose-900/40 p-3 text-xs text-rose-300">{error}</div>}<div className="mt-4 grid gap-3 md:grid-cols-4"><input aria-label="Variant SKU" placeholder="SKU" value={form.sku} onChange={(event) => setForm({ ...form, sku: event.target.value })} className="rounded-lg border border-slate-700 bg-slate-800 p-2 text-sm" /><input aria-label="Variant title" placeholder="Title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} className="rounded-lg border border-slate-700 bg-slate-800 p-2 text-sm" /><input aria-label="Variant price in poisha" type="number" min="1" placeholder="Price poisha" value={form.pricePoisha} onChange={(event) => setForm({ ...form, pricePoisha: event.target.value })} className="rounded-lg border border-slate-700 bg-slate-800 p-2 text-sm" /><input aria-label="Variant Product Point" type="number" min="0" placeholder="Product Point" value={form.productPoint} onChange={(event) => setForm({ ...form, productPoint: event.target.value })} className="rounded-lg border border-slate-700 bg-slate-800 p-2 text-sm" /></div><button type="button" disabled={saving || !form.sku || !form.title || !form.pricePoisha} onClick={() => void create()} className="mt-3 rounded-lg bg-orange-600 px-4 py-2 text-sm font-bold disabled:opacity-50">{saving ? 'Adding…' : 'Add variant'}</button>{variants.length > 0 && <ul className="mt-4 space-y-2">{variants.map((variant) => <li key={variant.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-800 p-3 text-sm"><span>{variant.title} · {variant.sku} · ৳{(variant.pricePoisha / 100).toLocaleString('en-BD', { minimumFractionDigits: 2 })} · {variant.productPoint} points</span><button type="button" onClick={() => void remove(variant)} className="text-xs font-bold text-rose-300 hover:underline">Delete</button></li>)}</ul>}</section>;
}
