'use client';

import { useCallback, useEffect, useState } from 'react';
import { Award, Loader2, RefreshCw } from 'lucide-react';

type Brand = { id: string; name: string; slug: string; website: string | null; approvalStatus: string; rejectionReason: string | null; version: number; isActive: boolean };

export default function BrandsAdminPage() {
  const [brands, setBrands] = useState<Brand[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [reason, setReason] = useState<Record<string, string>>({});
  const load = useCallback(async () => { try { setLoading(true); const response = await fetch('/api/v1/admin/brands'); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Unable to load brands.'); setBrands(json.data || []); } catch (err: any) { setError(err.message || 'Unable to load brands.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const review = async (brand: Brand, action: 'APPROVE' | 'REJECT') => { try { const response = await fetch(`/api/v1/admin/brands/${brand.id}/review`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, version: brand.version, reason: reason[brand.id] }) }); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Unable to review brand.'); await load(); } catch (err: any) { setError(err.message || 'Unable to review brand.'); } };
  return <main className="space-y-6 p-4 sm:p-6"><header className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-2xl bg-amber-50 p-3 text-amber-600"><Award className="h-6 w-6" /></div><div><h1 className="text-2xl font-black text-slate-900">Brands</h1><p className="text-sm text-slate-600">Governed brand registry and approval workflow.</p></div></div><button type="button" onClick={() => void load()} className="rounded-xl border border-slate-300 p-2"><RefreshCw className={loading ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} /></button></header>{error && <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{loading ? <div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" />Loading brands…</div> : <div className="grid gap-4">{brands.map((brand) => <article key={brand.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-black text-slate-900">{brand.name}</h2><p className="text-xs text-slate-500">/{brand.slug} · {brand.approvalStatus}</p>{brand.rejectionReason && <p className="mt-1 text-xs text-rose-700">{brand.rejectionReason}</p>}</div><div className="flex gap-2"><button type="button" onClick={() => void review(brand, 'APPROVE')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Approve</button><button type="button" onClick={() => void review(brand, 'REJECT')} className="rounded-lg bg-rose-600 px-3 py-2 text-xs font-bold text-white">Reject</button></div></div><textarea value={reason[brand.id] || ''} onChange={(event) => setReason((current) => ({ ...current, [brand.id]: event.target.value }))} placeholder="Rejection reason" className="mt-3 min-h-16 w-full rounded-xl border border-slate-300 p-3 text-sm" /></article>)}</div>}</main>;
}
