'use client';

import { useCallback, useEffect, useState } from 'react';

 type Review = { id: string; moderationStatus: string; duplicateStatus: string; severity: string; reason: string | null; product?: { id: string; title: string; slug: string; status: string } };

export default function ModerationPage() {
  const [reviews, setReviews] = useState<Review[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setLoading(true); const response = await fetch('/api/v1/admin/catalog/moderation?status=PENDING'); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Unable to load moderation queue.'); setReviews(json.data || []); setError(null); } catch (err: any) { setError(err.message || 'Unable to load moderation queue.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const resolve = async (review: Review, status: 'DISMISSED' | 'REQUEST_CHANGES' | 'APPROVED') => { const reason = window.prompt('Resolution reason'); if (!reason) return; try { const response = await fetch(`/api/v1/admin/catalog/moderation/${review.id}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, reason }) }); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Unable to resolve review.'); await load(); } catch (err: any) { setError(err.message || 'Unable to resolve review.'); } };
  return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><header><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Catalog Operations</p><h1 className="text-3xl font-black">Moderation and duplicate detection</h1><p className="mt-1 text-sm text-slate-600">Review deterministic duplicate candidates. Automated matches are advisory until an administrator resolves them.</p></header>{error && <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}<button type="button" onClick={() => void load()} className="ml-3 font-bold underline">Retry</button></div>}{loading ? <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Loading moderation queue…</div> : reviews.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">No pending moderation reviews.</div> : <div className="grid gap-4">{reviews.map((review) => <article key={review.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-black">{review.product?.title || review.product?.slug || review.id}</h2><p className="text-xs text-slate-500">Duplicate: {review.duplicateStatus} · Severity: {review.severity}</p><p className="mt-2 text-sm text-slate-600">{review.reason}</p></div><div className="flex gap-2"><button type="button" onClick={() => void resolve(review, 'DISMISSED')} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold">Dismiss</button><button type="button" onClick={() => void resolve(review, 'REQUEST_CHANGES')} className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-white">Request changes</button><button type="button" onClick={() => void resolve(review, 'APPROVED')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Approve</button></div></div></article>)}</div>}</div></main>;
}
