'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';

type Progress = { id: string; completedItems: string[]; dismissed: boolean; completionPercentage: number; template?: { name: string; locale: string; requiredFields: string[]; recommendedFields: string[]; mediaGuidance: string[]; titleExample?: string | null; descriptionExample?: string | null; validationHints: string[] } };

export default function SellerCatalogOnboardingPage() {
  const [items, setItems] = useState<Progress[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setLoading(true); const response = await fetch('/api/v1/seller/catalog/onboarding'); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Unable to load onboarding guidance.'); setItems(json.data || []); setError(null); } catch (err: any) { setError(err.message || 'Unable to load onboarding guidance.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <main className="min-h-screen bg-[#FAF9F6] p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-4xl space-y-6"><header className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-orange-600">Seller Catalog</p><h1 className="text-3xl font-black">Onboarding guidance</h1><p className="mt-1 text-sm text-slate-600">Complete the category-specific checklist before submitting products for approval.</p></div><Link href="/seller/products" className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold">Back to products</Link></header>{error && <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}<button type="button" onClick={() => void load()} className="ml-3 font-bold underline">Retry</button></div>}{loading ? <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Loading guidance…</div> : items.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">No onboarding progress is available yet. Start a product draft and select a category to receive guidance.</div> : <div className="space-y-4">{items.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-black">{item.template?.name || 'Catalog checklist'}</h2><p className="text-xs text-slate-500">{item.template?.locale || 'bn-BD'}</p></div><span className="rounded-full bg-orange-50 px-3 py-1 text-sm font-bold text-orange-700">{item.completionPercentage}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-orange-500" style={{ width: `${item.completionPercentage}%` }} /></div><div className="mt-5 grid gap-5 md:grid-cols-2"><section><h3 className="text-sm font-bold">Required before submission</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{(item.template?.requiredFields || []).map((field) => <li key={field}>{field}</li>)}</ul></section><section><h3 className="text-sm font-bold">Media guidance</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{(item.template?.mediaGuidance || []).map((hint) => <li key={hint}>{hint}</li>)}</ul></section></div>{item.template?.titleExample && <p className="mt-5 rounded-lg bg-slate-50 p-3 text-sm"><strong>Title example:</strong> {item.template.titleExample}</p>}{item.template?.descriptionExample && <p className="mt-2 rounded-lg bg-slate-50 p-3 text-sm"><strong>Description example:</strong> {item.template.descriptionExample}</p>}</article>)}</div>}</div></main>;
}
