'use client';

import { useState } from 'react';
import { csrfFetch } from '@/shared/security/csrf-client';

const sampleCsv = 'title,slug,description,categoryId,brandId,basePricePoisha,productPoint,sku,tags\nExample product,example-product,Description for example product,cat_example,brd_example,10000,10,SKU-EXAMPLE,example|demo';

export default function SellerCatalogBulkPage() {
  const [content, setContent] = useState(sampleCsv);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const runImport = async (mode: 'DRY_RUN' | 'COMMIT') => { try { setBusy(true); setError(null); const response = await csrfFetch('/api/v1/seller/catalog/imports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ format: 'CSV', content, mode, idempotencyKey: `seller-import-${Date.now()}` }) }); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Import failed.'); setMessage(mode === 'DRY_RUN' ? `Validation complete: ${json.data?.validation?.validRows ?? json.data?.job?.validRows ?? 0} valid rows.` : `Import committed: ${json.data?.commit?.committedRows ?? 0} products.`); } catch (err: any) { setError(err.message || 'Import failed.'); } finally { setBusy(false); } };
  const exportCatalog = async () => { try { setBusy(true); setError(null); const response = await csrfFetch('/api/v1/seller/catalog/exports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ format: 'CSV' }) }); const json = await response.json().catch(() => null); if (!response.ok || !json?.success) throw new Error(json?.error?.message || 'Import failed.'); if (json.data?.downloadUrl) window.open(json.data.downloadUrl, '_blank', 'noopener,noreferrer'); setMessage('Catalog export generated.'); } catch (err: any) { setError(err.message || 'Export failed.'); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-[#FAF9F6] p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-5xl space-y-6"><header><p className="text-xs font-bold uppercase tracking-widest text-orange-600">Seller Catalog</p><h1 className="text-3xl font-black">Bulk import and export</h1><p className="mt-1 text-sm text-slate-600">Run a dry validation before committing product drafts. Files remain in private object storage.</p></header>{message && <div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}{error && <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><label htmlFor="bulk-content" className="text-sm font-bold">CSV content</label><textarea id="bulk-content" value={content} onChange={(event) => setContent(event.target.value)} className="mt-3 min-h-64 w-full rounded-xl border border-slate-300 p-3 font-mono text-xs" /><div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled={busy} onClick={() => void runImport('DRY_RUN')} className="rounded-lg border border-orange-300 bg-orange-50 px-4 py-2 text-sm font-bold text-orange-700 disabled:opacity-50">Validate import</button><button type="button" disabled={busy} onClick={() => void runImport('COMMIT')} className="rounded-lg bg-orange-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Commit valid rows</button><button type="button" disabled={busy} onClick={() => void exportCatalog()} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Export catalog CSV</button></div></section></div></main>;
}
